/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package produk.UI;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
/**
 *
 * @author Reimark Samuel
 */
public class HalamanProduk extends javax.swing.JFrame {
DefaultListModel<String> produk = new DefaultListModel<>();
DefaultListModel<String> keranjang = new DefaultListModel<>();
Map<String, Produk> produkMap = new HashMap<>();
    /**
     * Creates new form HalamanProduk
     */
    public HalamanProduk() {
        initComponents();
        listProduk.setModel(produk);
        listKeranjang.setModel(keranjang);
        
        // Tambahkan produk ke dalam list
        addProduk(new Produk("Produk A", 10000, 10, "Deskripsi Produk A"));
        addProduk(new Produk("Produk B", 20000, 20, "Deskripsi Produk B"));
        addProduk(new Produk("Produk C", 30000, 30, "Deskripsi Produk C"));
        addProduk(new Produk("Produk D", 40000, 40, "Deskripsi Produk D"));
        
        listProduk.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    String selectedNamaProduk = listProduk.getSelectedValue();
                    if (selectedNamaProduk != null) {
                        Produk selectedProduk = produkMap.get(selectedNamaProduk);
                        if (selectedProduk != null) {
                            namaProdukLbl.setText(selectedProduk.getNama());
                            hargaLbl.setText(String.valueOf(selectedProduk.getHarga()));
                            stokLbl.setText(String.valueOf(selectedProduk.getStok()));
                            deskripsiLbl.setText(selectedProduk.getDeskripsi());
                        }
                    }
                }
            }
        });
    }

    private void addProduk(Produk produkObj) {
        produk.addElement(produkObj.getNama());
        produkMap.put(produkObj.getNama(), produkObj);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listProduk = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        namaProdukLbl = new javax.swing.JLabel();
        hargaLbl = new javax.swing.JLabel();
        deskripsiLbl = new javax.swing.JLabel();
        stokLbl = new javax.swing.JLabel();
        addKeranjang_btn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listKeranjang = new javax.swing.JList<>();
        bayarBtn = new javax.swing.JButton();
        hapusProdukBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jTabbedPane1ComponentHidden(evt);
            }
        });

        listProduk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listProdukMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listProduk);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Halaman Produk");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Pilih produk yang anda inginkan");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("Keterangan");

        namaProdukLbl.setText("Nama Produk");

        hargaLbl.setText("Harga");

        deskripsiLbl.setText("Deskripsi Produk");

        stokLbl.setText("Stok ");

        addKeranjang_btn.setText("Masukkan Keranjang");
        addKeranjang_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addKeranjang_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(namaProdukLbl)
                            .addComponent(hargaLbl)
                            .addComponent(deskripsiLbl)
                            .addComponent(stokLbl)
                            .addComponent(addKeranjang_btn)))
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(namaProdukLbl)
                        .addGap(18, 18, 18)
                        .addComponent(hargaLbl)
                        .addGap(18, 18, 18)
                        .addComponent(stokLbl)
                        .addGap(18, 18, 18)
                        .addComponent(deskripsiLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addKeranjang_btn)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Halaman Produk", jPanel1);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Keranjang");

        listKeranjang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listKeranjangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listKeranjang);
        listKeranjang.getAccessibleContext().setAccessibleDescription("");

        bayarBtn.setText("Bayar");
        bayarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bayarBtnActionPerformed(evt);
            }
        });

        hapusProdukBtn.setText("Hapus Produk");
        hapusProdukBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusProdukBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(bayarBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hapusProdukBtn)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bayarBtn)
                    .addComponent(hapusProdukBtn))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Keranjang", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane1ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTabbedPane1ComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane1ComponentHidden

    private void bayarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bayarBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bayarBtnActionPerformed

    private void hapusProdukBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusProdukBtnActionPerformed
        // TODO add your handling code here:
        int selectedIndex = listKeranjang.getSelectedIndex();
        if (selectedIndex != -1) {
            String selectedNamaProduk = listKeranjang.getSelectedValue();
            keranjang.removeElementAt(selectedIndex);
            JOptionPane.showMessageDialog(this, "Produk berhasil dihapus");
        } else {
            JOptionPane.showMessageDialog(this, "Pilih produk yang akan dihapus dari keranjang");
        }
    }//GEN-LAST:event_hapusProdukBtnActionPerformed

    private void addKeranjang_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addKeranjang_btnActionPerformed
        // TODO add your handling code here:
        int selectedIndex = listProduk.getSelectedIndex();
        if (selectedIndex != -1) {
            String selectedNamaProduk = listProduk.getSelectedValue();
            keranjang.addElement(selectedNamaProduk);
            JOptionPane.showMessageDialog(this, "Produk berhasil ditambahkan");
        } else {
            JOptionPane.showMessageDialog(this, "Pilih produk yang akan ditambahkan ke keranjang");
        }
    }//GEN-LAST:event_addKeranjang_btnActionPerformed

    private void listProdukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listProdukMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_listProdukMouseClicked

    private void listKeranjangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listKeranjangMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_listKeranjangMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HalamanProduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HalamanProduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HalamanProduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HalamanProduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HalamanProduk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addKeranjang_btn;
    private javax.swing.JButton bayarBtn;
    private javax.swing.JLabel deskripsiLbl;
    private javax.swing.JButton hapusProdukBtn;
    private javax.swing.JLabel hargaLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JList<String> listKeranjang;
    private javax.swing.JList<String> listProduk;
    private javax.swing.JLabel namaProdukLbl;
    private javax.swing.JLabel stokLbl;
    // End of variables declaration//GEN-END:variables
}

class Produk {
        private String nama;
        private double harga;
        private int stok;
        private String deskripsi;

        public Produk(String nama, double harga, int stok, String deskripsi) {
            this.nama = nama;
            this.harga = harga;
            this.stok = stok;
            this.deskripsi = deskripsi;
        }

        public String getNama() {
            return nama;
        }

        public double getHarga() {
            return harga;
        }

        public int getStok() {
            return stok;
        }

        public String getDeskripsi() {
            return deskripsi;
        }

        @Override
        public String toString() {
            return nama; // Untuk menampilkan nama produk di dalam JList
        }
    }